version: '3.8'
services:
  seismic:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/rstudio/earthquake
    environment:
      - DATA_DIR=/home/rstudio/earthquake/data
    command: ["bash", "-c", "scripts/build_report.sh"]
